extends: stylelint-config-standard-scss
rules:
  selector-class-pattern:
    - (^ck.*)|((^Mui[A-Z-])|^([a-z][a-z0-9]*)(-[a-z0-9]+)*$) # CKEditor, MUI or kebab-case
    - message: "Expected class selector to be kebab-case"
  no-descending-specificity: null
  font-family-no-missing-generic-family-keyword: null
  scss/at-extend-no-missing-placeholder: null
