version: '2.1'
services:
  python:
    build:
      context: .
      # TODO: upload dockerfile first then uncomment this line
      # dockerfile: ./travis/Dockerfile-travis-web
      dockerfile: ./Dockerfile
    environment:
      CELERY_TASK_ALWAYS_EAGER: 'True'
      SECRET_KEY: 'not_very_secret_key'

  web:
    build:
      context: .
      # TODO: upload dockerfile first then uncomment this line
      # dockerfile: ./travis/Dockerfile-travis-web
      dockerfile: ./Dockerfile
    environment:
      CELERY_TASK_ALWAYS_EAGER: 'True'
      SECRET_KEY: 'not_very_secret_key'

  celery:
    build:
      context: .
      # TODO: upload dockerfile first then uncomment this line
      # dockerfile: ./travis/Dockerfile-travis-web
      dockerfile: ./Dockerfile
    environment:
      # for celery, to avoid ImproperlyConfigured
      MAILGUN_URL: 'http://fake.example.com'
      MAILGUN_KEY: 'fake'
      CELERY_TASK_ALWAYS_EAGER: 'True'
      SECRET_KEY: 'not_very_secret_key'
