name: CI
on:
  push:
    branches:
      - master
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: OWASP ZAP Full Scan of Heroku CI
        uses: zaproxy/action-baseline@0.4.0
        with:
          target: ${{ secrets.ZAP_TARGET }}
          rules_file_name: '.zap/rules.tsv'
