name: CI
on:
  push:
    branches:
      - release
      - release-candidate
      - master
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: OWASP ZAP Baseline Scan of CI
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: ${{ secrets.ZAP_CI_TARGET }}
          rules_file_name: '.zap/rules.tsv'
      - name: OWASP ZAP Full Scan of RC
        if: ${{ github.ref == 'refs/heads/release-candidate' }}
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: ${{ secrets.ZAP_RC_TARGET }}
          rules_file_name: '.zap/rules.tsv'
      - name: OWASP ZAP Full Scan of Production
        if: ${{ github.ref == 'refs/heads/release' }}
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: ${{ secrets.ZAP_PROD_TARGET }}
          rules_file_name: '.zap/rules.tsv'
